---
- name: Install NGINX on WEB
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package presents
    apt:
     name: nginx
     state: present
  - name: Ensure that index.html presents
    copy:
     src: index.html
     dest: /var/www/html

  - name: Ensure nginx started
    service:
     name: nginx
     state: started

- name: Install POstgreSQL
  hosts: db
  become: yes

  tasks:
  - name: Ensure postgres pkg presents
    apt:
     name: postgresql
     state: present

  - name: install prerequisites
    apt:
     pkg:
     - libpq-dev
     - python-psycopg2
     - python3-psycopg2

  - name: Ensure postgres is started
    service:
     name: postgresql
     state: started
  - name: "Create app database"
    postgresql_db:
     state: present
     name: "test_db"
    become: yes
    become_user: postgres
