---
- name: Install NGINX
  hosts: mvn
  become: yes

  tasks:

  - name: Ensure NGINX package presents
    apt:
     name: nginx
     state: present

  - name: Ensure NGINX service is started
    service:
     name: nginx
     state: started

  - name: Replace line
    lineinfile:
     path:  /var/www/html/index.nginx-debian.html
     regexp: 'Welcome to nginx!'
     line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
