---
- name: Install MAVEN on MVN
  hosts: mvn
  become: yes
  vars:
   baseworkdir: /tmp/build/
  vars_files:
   - ./4maven.yml

  tasks:

  - name: Ensure jdk package presents
    apt:
     name: default-jdk
     state: present

  - name: Ensure git package presents
    apt:
     name: git
     state: present

  - name: Ensure maven package presents
    apt:
     name: maven
     state: present

  - name: Copy build params
    copy:
     src: 4maven.txt
     dest: '{{ baseworkdir }}'

  - name: Remove dir if exists
    file:
     path: "{{ baseworkdir }}{{ appdir.stdout }}"
     state: absent

  - name: Add environments and pull code
    git:
     repo: '{{ url4git.stdout }}'
     dest: "{{ baseworkdir }}{{ appdir.stdout }}"
     clone: yes
     update: yes

  - name: build code
    command: 'mvn -f {{ baseworkdir }}{{ appdir.stdout }}/pom.xml package'

  - name: Set list of files
    find:
     path: "{{ baseworkdir }}{{ appdir.stdout }}"
     file_type: file
     patterns: '*.war'
     recurse: yes #looking for wars in project folders
    register: war_files #list of paths to wars

  - name: Fetch war
    fetch:
     src: "{{ item.path }}" #attribute of the list entry
     dest: ./build/
     flat: yes
    with_items: "{{ war_files.files }}" #use list from dictionary

- name: Install Tomcat on TMCT
  hosts: tmct
  become: yes

  tasks:

  - name: Ensure jdk package presents
    apt:
     name: default-jdk
     state: present

  - name: Ensure tomcat package presents
    apt:
     name: tomcat9
     state: present

  - name: Ensure tomcat started
    service:
     name: tomcat9
     state: started

  - name: Copy package file
    copy:
     src: build/
     dest: /var/lib/tomcat9/webapps/
     owner: tomcat
     group: tomcat
