---
# tasks file for tomcat
- name: Ensure jdk package presents
  apt:
    name: default-jdk
    state: present

- name: Ensure tomcat package presents
  apt:
    name: tomcat9
    state: present

- name: Ensure tomcat started
  service:
    name: tomcat9
    state: started

- name: Remove dir if exists
  file:
   path: '{{item}}'
   state: absent
  with_items:
    - '{{ftoremove}}'
    - '{{dtoremove}}'