---
# tasks file for tomcat
- name: Ensure tomcat started
  service:
    name: tomcat9
    state: started

- name: Set list of files
  find:
    path: "{{ tomcatappdir }}"
    file_type: file
    patterns: '*.war'
    recurse: no #looking for wars in project folders
  register: war_files #list of paths to wars

- name: Remove app if exists
  file:
    path: "{{dtoremove}}"
    state: absent

- name: Remove war if exists
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ war_files.files }}"

- name: check app installed
  stat:
   path: "{{ dtoremove }}"
  notify:
  - restart_tomcat

