---
# tasks file for tomcat
- name: Remove dir if exists
  file:
   path: "{{ path_to_remove }}"
   state: absent

- name: Ensure jdk package presents
  apt:
    name: default-jdk
    state: present

- name: Ensure tomcat package presents
  apt:
    name: tomcat9
    state: present

- name: Ensure tomcat started
  service:
    name: tomcat9
    state: started
