---
# tasks file for common
- debug:
  msg: "{{smaven}}"
- name: fetch from mvn
  fetch:
   src: '{{keypath}}'
   dest: ./keys/maven.pub
   flat: yes
  when: ansible_default_ipv4.address == "{{smaven}}"
- name: fetch from tomcat
  fetch:
   src: '{{keypath}}'
   dest: ./keys/tomcat.pub
   flat: yes
  when: ansible_default_ipv4.address == "{{stomcat}}"
- name: install rsync
  apt:
   name: rsync
   state: present
- name: add keys maven
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', './keys/tomcat.pub') }}"
  when: ansible_default_ipv4.address == "{{smaven}}"
- name: add keys tomcat
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', './keys/maven.pub') }}"
  when: ansible_default_ipv4.address == "{{stomcat}}"
- name: install common apps
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - default-jdk

- name: install maven apps
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - git
    - maven
  when: ansible_default_ipv4.address == "{{smaven}}"

- name: install tomcat apps
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - tomcat9
  when: ansible_default_ipv4.address == "{{stomcat}}"
