---
# tasks file for common
- debug:
  msg: "{{smaven}}"
- name: fetch from mvn
  fetch:
   src: '{{keypath}}'
   dest: ./keys/maven.pub
   flat: yes
  when: ansible_default_ipv4.address == "{{smaven}}"
- name: fetch from mvn
  fetch:
   src: '{{keypath}}'
   dest: ./keys/tomcat.pub
   flat: yes
  when: ansible_default_ipv4.address == "{{stomcat}}"
- name: install rsync
  apt:
   name: rsync
   state: present
