---
# tasks file for common

- name: get keys
  hosts: tmcrole:mvnrole
  become: yes

  tasks:
    - name: fetch from mvn
      fetch:
       src: {{keypath}}
       dest: ./keys/{{smaven}}.pub
       flat: yes
      when: ansible_default_ipv4.address == {{smaven}}
    - name: fetch from mvn
      fetch:
        src: {{keypath}}
        dest: ./keys/{{stomcat}}.pub
        flat: yes
      when: ansible_default_ipv4.address == {{stomcat}}
