---
# tasks file for maven
- name: Remove dir if exists
  file:
   path: "{{ baseworkdir }}{{ appdir }}"
   state: absent

- name: Add environments and pull code
  git:
   repo: '{{ url4git }}'
   dest: "{{ baseworkdir }}{{ appdir }}"
   clone: yes
   update: yes

- name: build code
  command: 'mvn -f {{ baseworkdir }}{{ appdir }}/pom.xml package'

- name: Set list of files
  find:
   path: "{{ baseworkdir }}{{ appdir }}"
   file_type: file
   patterns: '*.war'
   recurse: yes #looking for wars in project folders
  register: war_files #list of paths to wars

